---

dist: bionic
language: r
r: release

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library

install:
  - Rscript -f install_dependencies.R
  
script:
  - Rscript -f deploy.R
